services:
  - type: web
    name: echo-server
    runtime: docker
    plan: free
    region: frankfurt
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: BETTER_AUTH_SECRET
        generateValue: true
      - key: BETTER_AUTH_URL
        sync: false
